baseURL = "https://ashitovod.com/"
title = "be clever is the new black"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

languageCode = "ru"
defaultContentLanguage = "ru"

theme = "minimo"

paginate = 10
enableGitInfo = true
enableRobotsTXT = true
googleAnalytics = "UA-128111087-1"
metaDataFormat = "yaml"
# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true
pygmentsStyle = "colorful"
preserveTaxonomyNames = true
enableEmoji = true

[params.info]
    description = "be clever is the new black"
    title404 = "Страница не найдена"

[params.assets]
    favicon = "favicon.ico"
    customCSS = ["/assets/custom.css"]
    gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
    prefix = ""
    holder = "ashitovod"
    startYear = "2018"
    suffix = ""

[params.settings]
    dateFormat = "2006-01-02"
    listDateFormat = "2006-01-02"
    archiveDateFormat = "02.01"
    hideEntryNavigation = ["page"] # boolean / array of sections
    showReadingTime = true
    taxonomyCloudShuffle = false
    accentColor = "#ffcd00"
    hideMainMenu = false

[params.sidebar]
    enable = true

[params.widgets]
    homepage = ["recent_posts"]
    sidebar = ["about", "social_menu", "sidebar_menu", "taxonomy_cloud"]
    footer = []

[params.social]
    email = "asarmakeeva@gmail.com"
    github = "asarmakeeva"
    twitter = "ashitovod"
    telegram = "ashitovod"
    instagram = "ashitovod"

[params.comments]
    enable = false

[taxonomies]
    category = "categories"
    tag = "tags"

[sitemap]
    changefreq = "monthly"
    filename = "sitemap.xml"
    priority = 0.5

[blackfriday]
    extensions = ["noEmptyLineBeforeBlock"]
